DROP TABLE phx_accidents;


-- Create Us_Accidents_2023_Arizona table schema
CREATE TABLE phx_accidents (
	Accident_Date Date,
	Accident_Time Time,
	ID VARCHAR (100),
 	Severity INT,
 	Start_Lat FLOAT,
 	Start_Lng FLOAT,
 	End_Lat FLOAT,
 	End_Lng FLOAT,
 	"Distance(mi)" FLOAT,
 	Description VARCHAR (500),
 	Street VARCHAR (50),
 	City VARCHAR (50),
 	County VARCHAR (50),
 	State VARCHAR (50),
 	Zipcode INT,
 	Country VARCHAR (100),
 	Timezone VARCHAR (100),
 	Airport_Code VARCHAR (100),
 	"Temperature(F)" FLOAT,
 	"Wind_Chill(F)" FLOAT,
 	"Humidity(%)" FLOAT,
 	"Pressure(in)" FLOAT,
 	"Visibility(mi)" FLOAT,
 	Wind_Direction VARCHAR (5),
 	"Wind_Speed(mph)" FLOAT,
 	"Precipitation(in)" FLOAT,
 	Weather_Condition VARCHAR (50),
 	Amenity BOOLEAN,
 	Bump BOOLEAN,
 	Crossing BOOLEAN,
 	Give_Way BOOLEAN,
 	Junction BOOLEAN,
 	No_Exit BOOLEAN,
  	Railway BOOLEAN,
 	Stop BOOLEAN,
  	Traffic_Calming BOOLEAN,
 	Traffic_Signal BOOLEAN,
 	Day_or_Night VARCHAR (10)
);